// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dao

import (
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/waifuvault/WaifuVault/thumbnails/pkg/mod"
	"gorm.io/gorm"
)

// NewMockDao creates a new instance of MockDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDao {
	mock := &MockDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDao is an autogenerated mock type for the Dao type
type MockDao struct {
	mock.Mock
}

type MockDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDao) EXPECT() *MockDao_Expecter {
	return &MockDao_Expecter{mock: &_m.Mock}
}

// GetFileEntry provides a mock function for the type MockDao
func (_mock *MockDao) GetFileEntry(token uuid.UUID, tx ...*gorm.DB) (*mod.FileEntry, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(token, tx)
	} else {
		tmpRet = _mock.Called(token)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetFileEntry")
	}

	var r0 *mod.FileEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, ...*gorm.DB) (*mod.FileEntry, error)); ok {
		return returnFunc(token, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, ...*gorm.DB) *mod.FileEntry); ok {
		r0 = returnFunc(token, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mod.FileEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, ...*gorm.DB) error); ok {
		r1 = returnFunc(token, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDao_GetFileEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileEntry'
type MockDao_GetFileEntry_Call struct {
	*mock.Call
}

// GetFileEntry is a helper method to define mock.On call
//   - token uuid.UUID
//   - tx ...*gorm.DB
func (_e *MockDao_Expecter) GetFileEntry(token interface{}, tx ...interface{}) *MockDao_GetFileEntry_Call {
	return &MockDao_GetFileEntry_Call{Call: _e.mock.On("GetFileEntry",
		append([]interface{}{token}, tx...)...)}
}

func (_c *MockDao_GetFileEntry_Call) Run(run func(token uuid.UUID, tx ...*gorm.DB)) *MockDao_GetFileEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 []*gorm.DB
		var variadicArgs []*gorm.DB
		if len(args) > 1 {
			variadicArgs = args[1].([]*gorm.DB)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockDao_GetFileEntry_Call) Return(fileEntry *mod.FileEntry, err error) *MockDao_GetFileEntry_Call {
	_c.Call.Return(fileEntry, err)
	return _c
}

func (_c *MockDao_GetFileEntry_Call) RunAndReturn(run func(token uuid.UUID, tx ...*gorm.DB) (*mod.FileEntry, error)) *MockDao_GetFileEntry_Call {
	_c.Call.Return(run)
	return _c
}

// SaveThumbnails provides a mock function for the type MockDao
func (_mock *MockDao) SaveThumbnails(thumbnails []mod.Thumbnail, tx ...*gorm.DB) ([]mod.Thumbnail, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(thumbnails, tx)
	} else {
		tmpRet = _mock.Called(thumbnails)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SaveThumbnails")
	}

	var r0 []mod.Thumbnail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]mod.Thumbnail, ...*gorm.DB) ([]mod.Thumbnail, error)); ok {
		return returnFunc(thumbnails, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func([]mod.Thumbnail, ...*gorm.DB) []mod.Thumbnail); ok {
		r0 = returnFunc(thumbnails, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]mod.Thumbnail)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]mod.Thumbnail, ...*gorm.DB) error); ok {
		r1 = returnFunc(thumbnails, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDao_SaveThumbnails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveThumbnails'
type MockDao_SaveThumbnails_Call struct {
	*mock.Call
}

// SaveThumbnails is a helper method to define mock.On call
//   - thumbnails []mod.Thumbnail
//   - tx ...*gorm.DB
func (_e *MockDao_Expecter) SaveThumbnails(thumbnails interface{}, tx ...interface{}) *MockDao_SaveThumbnails_Call {
	return &MockDao_SaveThumbnails_Call{Call: _e.mock.On("SaveThumbnails",
		append([]interface{}{thumbnails}, tx...)...)}
}

func (_c *MockDao_SaveThumbnails_Call) Run(run func(thumbnails []mod.Thumbnail, tx ...*gorm.DB)) *MockDao_SaveThumbnails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []mod.Thumbnail
		if args[0] != nil {
			arg0 = args[0].([]mod.Thumbnail)
		}
		var arg1 []*gorm.DB
		var variadicArgs []*gorm.DB
		if len(args) > 1 {
			variadicArgs = args[1].([]*gorm.DB)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockDao_SaveThumbnails_Call) Return(thumbnails1 []mod.Thumbnail, err error) *MockDao_SaveThumbnails_Call {
	_c.Call.Return(thumbnails1, err)
	return _c
}

func (_c *MockDao_SaveThumbnails_Call) RunAndReturn(run func(thumbnails []mod.Thumbnail, tx ...*gorm.DB) ([]mod.Thumbnail, error)) *MockDao_SaveThumbnails_Call {
	_c.Call.Return(run)
	return _c
}
