// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package thumbnail

import (
	"sync"

	mock "github.com/stretchr/testify/mock"
	"github.com/waifuvault/WaifuVault/thumbnails/pkg/dto"
	"github.com/waifuvault/WaifuVault/thumbnails/pkg/mod"
)

// NewMockBatchProcessor creates a new instance of MockBatchProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBatchProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBatchProcessor {
	mock := &MockBatchProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBatchProcessor is an autogenerated mock type for the BatchProcessor type
type MockBatchProcessor struct {
	mock.Mock
}

type MockBatchProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBatchProcessor) EXPECT() *MockBatchProcessor_Expecter {
	return &MockBatchProcessor_Expecter{mock: &_m.Mock}
}

// Process provides a mock function for the type MockBatchProcessor
func (_mock *MockBatchProcessor) Process() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBatchProcessor_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type MockBatchProcessor_Process_Call struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
func (_e *MockBatchProcessor_Expecter) Process() *MockBatchProcessor_Process_Call {
	return &MockBatchProcessor_Process_Call{Call: _e.mock.On("Process")}
}

func (_c *MockBatchProcessor_Process_Call) Run(run func()) *MockBatchProcessor_Process_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBatchProcessor_Process_Call) Return(err error) *MockBatchProcessor_Process_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBatchProcessor_Process_Call) RunAndReturn(run func() error) *MockBatchProcessor_Process_Call {
	_c.Call.Return(run)
	return _c
}

// batchProcess provides a mock function for the type MockBatchProcessor
func (_mock *MockBatchProcessor) batchProcess(resultsChan <-chan mod.Thumbnail, done chan<- struct{}) {
	_mock.Called(resultsChan, done)
	return
}

// MockBatchProcessor_batchProcess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'batchProcess'
type MockBatchProcessor_batchProcess_Call struct {
	*mock.Call
}

// batchProcess is a helper method to define mock.On call
//   - resultsChan <-chan mod.Thumbnail
//   - done chan<- struct{}
func (_e *MockBatchProcessor_Expecter) batchProcess(resultsChan interface{}, done interface{}) *MockBatchProcessor_batchProcess_Call {
	return &MockBatchProcessor_batchProcess_Call{Call: _e.mock.On("batchProcess", resultsChan, done)}
}

func (_c *MockBatchProcessor_batchProcess_Call) Run(run func(resultsChan <-chan mod.Thumbnail, done chan<- struct{})) *MockBatchProcessor_batchProcess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 <-chan mod.Thumbnail
		if args[0] != nil {
			arg0 = args[0].(<-chan mod.Thumbnail)
		}
		var arg1 chan<- struct{}
		if args[1] != nil {
			arg1 = args[1].(chan<- struct{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBatchProcessor_batchProcess_Call) Return() *MockBatchProcessor_batchProcess_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBatchProcessor_batchProcess_Call) RunAndReturn(run func(resultsChan <-chan mod.Thumbnail, done chan<- struct{})) *MockBatchProcessor_batchProcess_Call {
	_c.Run(run)
	return _c
}

// thumbnailWorker provides a mock function for the type MockBatchProcessor
func (_mock *MockBatchProcessor) thumbnailWorker(wg *sync.WaitGroup, filesChan <-chan dto.FileEntryDto, resultsChan chan<- mod.Thumbnail) {
	_mock.Called(wg, filesChan, resultsChan)
	return
}

// MockBatchProcessor_thumbnailWorker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'thumbnailWorker'
type MockBatchProcessor_thumbnailWorker_Call struct {
	*mock.Call
}

// thumbnailWorker is a helper method to define mock.On call
//   - wg *sync.WaitGroup
//   - filesChan <-chan dto.FileEntryDto
//   - resultsChan chan<- mod.Thumbnail
func (_e *MockBatchProcessor_Expecter) thumbnailWorker(wg interface{}, filesChan interface{}, resultsChan interface{}) *MockBatchProcessor_thumbnailWorker_Call {
	return &MockBatchProcessor_thumbnailWorker_Call{Call: _e.mock.On("thumbnailWorker", wg, filesChan, resultsChan)}
}

func (_c *MockBatchProcessor_thumbnailWorker_Call) Run(run func(wg *sync.WaitGroup, filesChan <-chan dto.FileEntryDto, resultsChan chan<- mod.Thumbnail)) *MockBatchProcessor_thumbnailWorker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *sync.WaitGroup
		if args[0] != nil {
			arg0 = args[0].(*sync.WaitGroup)
		}
		var arg1 <-chan dto.FileEntryDto
		if args[1] != nil {
			arg1 = args[1].(<-chan dto.FileEntryDto)
		}
		var arg2 chan<- mod.Thumbnail
		if args[2] != nil {
			arg2 = args[2].(chan<- mod.Thumbnail)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBatchProcessor_thumbnailWorker_Call) Return() *MockBatchProcessor_thumbnailWorker_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBatchProcessor_thumbnailWorker_Call) RunAndReturn(run func(wg *sync.WaitGroup, filesChan <-chan dto.FileEntryDto, resultsChan chan<- mod.Thumbnail)) *MockBatchProcessor_thumbnailWorker_Call {
	_c.Run(run)
	return _c
}
