// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package thumbnail

import (
	"mime/multipart"

	mock "github.com/stretchr/testify/mock"
	"github.com/waifuvault/WaifuVault/thumbnails/pkg/dto"
)

// NewMockProcessor creates a new instance of MockProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProcessor {
	mock := &MockProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProcessor is an autogenerated mock type for the Processor type
type MockProcessor struct {
	mock.Mock
}

type MockProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProcessor) EXPECT() *MockProcessor_Expecter {
	return &MockProcessor_Expecter{mock: &_m.Mock}
}

// GenerateThumbnail provides a mock function for the type MockProcessor
func (_mock *MockProcessor) GenerateThumbnail(fileEntry dto.FileEntryDto, animate bool) ([]byte, error) {
	ret := _mock.Called(fileEntry, animate)

	if len(ret) == 0 {
		panic("no return value specified for GenerateThumbnail")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(dto.FileEntryDto, bool) ([]byte, error)); ok {
		return returnFunc(fileEntry, animate)
	}
	if returnFunc, ok := ret.Get(0).(func(dto.FileEntryDto, bool) []byte); ok {
		r0 = returnFunc(fileEntry, animate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(dto.FileEntryDto, bool) error); ok {
		r1 = returnFunc(fileEntry, animate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProcessor_GenerateThumbnail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateThumbnail'
type MockProcessor_GenerateThumbnail_Call struct {
	*mock.Call
}

// GenerateThumbnail is a helper method to define mock.On call
//   - fileEntry dto.FileEntryDto
//   - animate bool
func (_e *MockProcessor_Expecter) GenerateThumbnail(fileEntry interface{}, animate interface{}) *MockProcessor_GenerateThumbnail_Call {
	return &MockProcessor_GenerateThumbnail_Call{Call: _e.mock.On("GenerateThumbnail", fileEntry, animate)}
}

func (_c *MockProcessor_GenerateThumbnail_Call) Run(run func(fileEntry dto.FileEntryDto, animate bool)) *MockProcessor_GenerateThumbnail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dto.FileEntryDto
		if args[0] != nil {
			arg0 = args[0].(dto.FileEntryDto)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProcessor_GenerateThumbnail_Call) Return(bytes []byte, err error) *MockProcessor_GenerateThumbnail_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockProcessor_GenerateThumbnail_Call) RunAndReturn(run func(fileEntry dto.FileEntryDto, animate bool) ([]byte, error)) *MockProcessor_GenerateThumbnail_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateThumbnailFromMultipart provides a mock function for the type MockProcessor
func (_mock *MockProcessor) GenerateThumbnailFromMultipart(file multipart.File, header *multipart.FileHeader, animate bool) ([]byte, error) {
	ret := _mock.Called(file, header, animate)

	if len(ret) == 0 {
		panic("no return value specified for GenerateThumbnailFromMultipart")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(multipart.File, *multipart.FileHeader, bool) ([]byte, error)); ok {
		return returnFunc(file, header, animate)
	}
	if returnFunc, ok := ret.Get(0).(func(multipart.File, *multipart.FileHeader, bool) []byte); ok {
		r0 = returnFunc(file, header, animate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(multipart.File, *multipart.FileHeader, bool) error); ok {
		r1 = returnFunc(file, header, animate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProcessor_GenerateThumbnailFromMultipart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateThumbnailFromMultipart'
type MockProcessor_GenerateThumbnailFromMultipart_Call struct {
	*mock.Call
}

// GenerateThumbnailFromMultipart is a helper method to define mock.On call
//   - file multipart.File
//   - header *multipart.FileHeader
//   - animate bool
func (_e *MockProcessor_Expecter) GenerateThumbnailFromMultipart(file interface{}, header interface{}, animate interface{}) *MockProcessor_GenerateThumbnailFromMultipart_Call {
	return &MockProcessor_GenerateThumbnailFromMultipart_Call{Call: _e.mock.On("GenerateThumbnailFromMultipart", file, header, animate)}
}

func (_c *MockProcessor_GenerateThumbnailFromMultipart_Call) Run(run func(file multipart.File, header *multipart.FileHeader, animate bool)) *MockProcessor_GenerateThumbnailFromMultipart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 multipart.File
		if args[0] != nil {
			arg0 = args[0].(multipart.File)
		}
		var arg1 *multipart.FileHeader
		if args[1] != nil {
			arg1 = args[1].(*multipart.FileHeader)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProcessor_GenerateThumbnailFromMultipart_Call) Return(bytes []byte, err error) *MockProcessor_GenerateThumbnailFromMultipart_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockProcessor_GenerateThumbnailFromMultipart_Call) RunAndReturn(run func(file multipart.File, header *multipart.FileHeader, animate bool) ([]byte, error)) *MockProcessor_GenerateThumbnailFromMultipart_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateThumbnailFromURL provides a mock function for the type MockProcessor
func (_mock *MockProcessor) GenerateThumbnailFromURL(url string, animate bool) ([]byte, error) {
	ret := _mock.Called(url, animate)

	if len(ret) == 0 {
		panic("no return value specified for GenerateThumbnailFromURL")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, bool) ([]byte, error)); ok {
		return returnFunc(url, animate)
	}
	if returnFunc, ok := ret.Get(0).(func(string, bool) []byte); ok {
		r0 = returnFunc(url, animate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, bool) error); ok {
		r1 = returnFunc(url, animate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProcessor_GenerateThumbnailFromURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateThumbnailFromURL'
type MockProcessor_GenerateThumbnailFromURL_Call struct {
	*mock.Call
}

// GenerateThumbnailFromURL is a helper method to define mock.On call
//   - url string
//   - animate bool
func (_e *MockProcessor_Expecter) GenerateThumbnailFromURL(url interface{}, animate interface{}) *MockProcessor_GenerateThumbnailFromURL_Call {
	return &MockProcessor_GenerateThumbnailFromURL_Call{Call: _e.mock.On("GenerateThumbnailFromURL", url, animate)}
}

func (_c *MockProcessor_GenerateThumbnailFromURL_Call) Run(run func(url string, animate bool)) *MockProcessor_GenerateThumbnailFromURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProcessor_GenerateThumbnailFromURL_Call) Return(bytes []byte, err error) *MockProcessor_GenerateThumbnailFromURL_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockProcessor_GenerateThumbnailFromURL_Call) RunAndReturn(run func(url string, animate bool) ([]byte, error)) *MockProcessor_GenerateThumbnailFromURL_Call {
	_c.Call.Return(run)
	return _c
}

// SupportsFile provides a mock function for the type MockProcessor
func (_mock *MockProcessor) SupportsFile(fileEntry dto.FileEntryDto) bool {
	ret := _mock.Called(fileEntry)

	if len(ret) == 0 {
		panic("no return value specified for SupportsFile")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(dto.FileEntryDto) bool); ok {
		r0 = returnFunc(fileEntry)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockProcessor_SupportsFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportsFile'
type MockProcessor_SupportsFile_Call struct {
	*mock.Call
}

// SupportsFile is a helper method to define mock.On call
//   - fileEntry dto.FileEntryDto
func (_e *MockProcessor_Expecter) SupportsFile(fileEntry interface{}) *MockProcessor_SupportsFile_Call {
	return &MockProcessor_SupportsFile_Call{Call: _e.mock.On("SupportsFile", fileEntry)}
}

func (_c *MockProcessor_SupportsFile_Call) Run(run func(fileEntry dto.FileEntryDto)) *MockProcessor_SupportsFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dto.FileEntryDto
		if args[0] != nil {
			arg0 = args[0].(dto.FileEntryDto)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProcessor_SupportsFile_Call) Return(b bool) *MockProcessor_SupportsFile_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockProcessor_SupportsFile_Call) RunAndReturn(run func(fileEntry dto.FileEntryDto) bool) *MockProcessor_SupportsFile_Call {
	_c.Call.Return(run)
	return _c
}

// SupportsMultipartFile provides a mock function for the type MockProcessor
func (_mock *MockProcessor) SupportsMultipartFile(header *multipart.FileHeader) bool {
	ret := _mock.Called(header)

	if len(ret) == 0 {
		panic("no return value specified for SupportsMultipartFile")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(*multipart.FileHeader) bool); ok {
		r0 = returnFunc(header)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockProcessor_SupportsMultipartFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportsMultipartFile'
type MockProcessor_SupportsMultipartFile_Call struct {
	*mock.Call
}

// SupportsMultipartFile is a helper method to define mock.On call
//   - header *multipart.FileHeader
func (_e *MockProcessor_Expecter) SupportsMultipartFile(header interface{}) *MockProcessor_SupportsMultipartFile_Call {
	return &MockProcessor_SupportsMultipartFile_Call{Call: _e.mock.On("SupportsMultipartFile", header)}
}

func (_c *MockProcessor_SupportsMultipartFile_Call) Run(run func(header *multipart.FileHeader)) *MockProcessor_SupportsMultipartFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *multipart.FileHeader
		if args[0] != nil {
			arg0 = args[0].(*multipart.FileHeader)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProcessor_SupportsMultipartFile_Call) Return(b bool) *MockProcessor_SupportsMultipartFile_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockProcessor_SupportsMultipartFile_Call) RunAndReturn(run func(header *multipart.FileHeader) bool) *MockProcessor_SupportsMultipartFile_Call {
	_c.Call.Return(run)
	return _c
}
