// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package thumbnail

import (
	"mime/multipart"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/waifuvault/WaifuVault/thumbnails/pkg/dto"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// GenerateThumbnail provides a mock function for the type MockService
func (_mock *MockService) GenerateThumbnail(header *multipart.FileHeader, animate bool) ([]byte, error) {
	ret := _mock.Called(header, animate)

	if len(ret) == 0 {
		panic("no return value specified for GenerateThumbnail")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*multipart.FileHeader, bool) ([]byte, error)); ok {
		return returnFunc(header, animate)
	}
	if returnFunc, ok := ret.Get(0).(func(*multipart.FileHeader, bool) []byte); ok {
		r0 = returnFunc(header, animate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*multipart.FileHeader, bool) error); ok {
		r1 = returnFunc(header, animate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GenerateThumbnail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateThumbnail'
type MockService_GenerateThumbnail_Call struct {
	*mock.Call
}

// GenerateThumbnail is a helper method to define mock.On call
//   - header *multipart.FileHeader
//   - animate bool
func (_e *MockService_Expecter) GenerateThumbnail(header interface{}, animate interface{}) *MockService_GenerateThumbnail_Call {
	return &MockService_GenerateThumbnail_Call{Call: _e.mock.On("GenerateThumbnail", header, animate)}
}

func (_c *MockService_GenerateThumbnail_Call) Run(run func(header *multipart.FileHeader, animate bool)) *MockService_GenerateThumbnail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *multipart.FileHeader
		if args[0] != nil {
			arg0 = args[0].(*multipart.FileHeader)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GenerateThumbnail_Call) Return(bytes []byte, err error) *MockService_GenerateThumbnail_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockService_GenerateThumbnail_Call) RunAndReturn(run func(header *multipart.FileHeader, animate bool) ([]byte, error)) *MockService_GenerateThumbnail_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateThumbnailByToken provides a mock function for the type MockService
func (_mock *MockService) GenerateThumbnailByToken(fileToken uuid.UUID, animate bool) ([]byte, error) {
	ret := _mock.Called(fileToken, animate)

	if len(ret) == 0 {
		panic("no return value specified for GenerateThumbnailByToken")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, bool) ([]byte, error)); ok {
		return returnFunc(fileToken, animate)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, bool) []byte); ok {
		r0 = returnFunc(fileToken, animate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, bool) error); ok {
		r1 = returnFunc(fileToken, animate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GenerateThumbnailByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateThumbnailByToken'
type MockService_GenerateThumbnailByToken_Call struct {
	*mock.Call
}

// GenerateThumbnailByToken is a helper method to define mock.On call
//   - fileToken uuid.UUID
//   - animate bool
func (_e *MockService_Expecter) GenerateThumbnailByToken(fileToken interface{}, animate interface{}) *MockService_GenerateThumbnailByToken_Call {
	return &MockService_GenerateThumbnailByToken_Call{Call: _e.mock.On("GenerateThumbnailByToken", fileToken, animate)}
}

func (_c *MockService_GenerateThumbnailByToken_Call) Run(run func(fileToken uuid.UUID, animate bool)) *MockService_GenerateThumbnailByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GenerateThumbnailByToken_Call) Return(bytes []byte, err error) *MockService_GenerateThumbnailByToken_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockService_GenerateThumbnailByToken_Call) RunAndReturn(run func(fileToken uuid.UUID, animate bool) ([]byte, error)) *MockService_GenerateThumbnailByToken_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateThumbnailFromURL provides a mock function for the type MockService
func (_mock *MockService) GenerateThumbnailFromURL(url string, animate bool) ([]byte, error) {
	ret := _mock.Called(url, animate)

	if len(ret) == 0 {
		panic("no return value specified for GenerateThumbnailFromURL")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, bool) ([]byte, error)); ok {
		return returnFunc(url, animate)
	}
	if returnFunc, ok := ret.Get(0).(func(string, bool) []byte); ok {
		r0 = returnFunc(url, animate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, bool) error); ok {
		r1 = returnFunc(url, animate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GenerateThumbnailFromURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateThumbnailFromURL'
type MockService_GenerateThumbnailFromURL_Call struct {
	*mock.Call
}

// GenerateThumbnailFromURL is a helper method to define mock.On call
//   - url string
//   - animate bool
func (_e *MockService_Expecter) GenerateThumbnailFromURL(url interface{}, animate interface{}) *MockService_GenerateThumbnailFromURL_Call {
	return &MockService_GenerateThumbnailFromURL_Call{Call: _e.mock.On("GenerateThumbnailFromURL", url, animate)}
}

func (_c *MockService_GenerateThumbnailFromURL_Call) Run(run func(url string, animate bool)) *MockService_GenerateThumbnailFromURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GenerateThumbnailFromURL_Call) Return(bytes []byte, err error) *MockService_GenerateThumbnailFromURL_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockService_GenerateThumbnailFromURL_Call) RunAndReturn(run func(url string, animate bool) ([]byte, error)) *MockService_GenerateThumbnailFromURL_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateThumbnails provides a mock function for the type MockService
func (_mock *MockService) GenerateThumbnails(files []dto.FileEntryDto, album int) error {
	ret := _mock.Called(files, album)

	if len(ret) == 0 {
		panic("no return value specified for GenerateThumbnails")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]dto.FileEntryDto, int) error); ok {
		r0 = returnFunc(files, album)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_GenerateThumbnails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateThumbnails'
type MockService_GenerateThumbnails_Call struct {
	*mock.Call
}

// GenerateThumbnails is a helper method to define mock.On call
//   - files []dto.FileEntryDto
//   - album int
func (_e *MockService_Expecter) GenerateThumbnails(files interface{}, album interface{}) *MockService_GenerateThumbnails_Call {
	return &MockService_GenerateThumbnails_Call{Call: _e.mock.On("GenerateThumbnails", files, album)}
}

func (_c *MockService_GenerateThumbnails_Call) Run(run func(files []dto.FileEntryDto, album int)) *MockService_GenerateThumbnails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []dto.FileEntryDto
		if args[0] != nil {
			arg0 = args[0].([]dto.FileEntryDto)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GenerateThumbnails_Call) Return(err error) *MockService_GenerateThumbnails_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_GenerateThumbnails_Call) RunAndReturn(run func(files []dto.FileEntryDto, album int) error) *MockService_GenerateThumbnails_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllSupportedExtensions provides a mock function for the type MockService
func (_mock *MockService) GetAllSupportedExtensions() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllSupportedExtensions")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockService_GetAllSupportedExtensions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllSupportedExtensions'
type MockService_GetAllSupportedExtensions_Call struct {
	*mock.Call
}

// GetAllSupportedExtensions is a helper method to define mock.On call
func (_e *MockService_Expecter) GetAllSupportedExtensions() *MockService_GetAllSupportedExtensions_Call {
	return &MockService_GetAllSupportedExtensions_Call{Call: _e.mock.On("GetAllSupportedExtensions")}
}

func (_c *MockService_GetAllSupportedExtensions_Call) Run(run func()) *MockService_GetAllSupportedExtensions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_GetAllSupportedExtensions_Call) Return(strings []string) *MockService_GetAllSupportedExtensions_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockService_GetAllSupportedExtensions_Call) RunAndReturn(run func() []string) *MockService_GetAllSupportedExtensions_Call {
	_c.Call.Return(run)
	return _c
}

// IsAlbumLoading provides a mock function for the type MockService
func (_mock *MockService) IsAlbumLoading(album int) bool {
	ret := _mock.Called(album)

	if len(ret) == 0 {
		panic("no return value specified for IsAlbumLoading")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(int) bool); ok {
		r0 = returnFunc(album)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockService_IsAlbumLoading_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAlbumLoading'
type MockService_IsAlbumLoading_Call struct {
	*mock.Call
}

// IsAlbumLoading is a helper method to define mock.On call
//   - album int
func (_e *MockService_Expecter) IsAlbumLoading(album interface{}) *MockService_IsAlbumLoading_Call {
	return &MockService_IsAlbumLoading_Call{Call: _e.mock.On("IsAlbumLoading", album)}
}

func (_c *MockService_IsAlbumLoading_Call) Run(run func(album int)) *MockService_IsAlbumLoading_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_IsAlbumLoading_Call) Return(b bool) *MockService_IsAlbumLoading_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockService_IsAlbumLoading_Call) RunAndReturn(run func(album int) bool) *MockService_IsAlbumLoading_Call {
	_c.Call.Return(run)
	return _c
}
